type VideoDeepLinks = {
    metaDetailsStreams: string,
    player: string | null,
    externalPlayer: ExternalPlayerLinks | null,
};

type Video = {
    id: string,
    title: string,
    overview: string | null,
    released: string | null,
    thumbnail: string | null,
    season?: number,
    episode?: number,
    streams: Stream[],
    trailerStreams: TrailerStream[],
    watched: boolean,
    progress: number,
    upcoming: boolean,
    deepLinks: VideoDeepLinks,
    scheduled: boolean,
    startTime?: string | null,
    endTime?: string | null,
    runtime?: string | null,
    releaseInfo?: string | null,
    genres?: string[],
    cast?: string[],
    director?: string[],
    links?: Link[],
};
